ci: pbxproj imzasiz yama CRLF-duyarsiz olsun (imzasiz IPA uretimi)

diff --git a/.github/workflows/ios-build-release.yml b/.github/workflows/ios-build-release.yml
--- a/.github/workflows/ios-build-release.yml
+++ b/.github/workflows/ios-build-release.yml
@@ -44,12 +44,20 @@ jobs:
         run: |
           cd ios
           python3 - <<'PY'
+          import re
           p = 'Runner.xcodeproj/project.pbxproj'
           s = open(p).read()
-          s = s.replace('CODE_SIGN_STYLE = Automatic;\n',
-                        'CODE_SIGN_STYLE = Automatic;\n\t\t\t\tDEVELOPMENT_TEAM = "AAAAAAAAAA";\n\t\t\t\tCODE_SIGNING_ALLOWED = NO;\n')
-          open(p, 'w').write(s)
+          def repl(m):
+              eol = m.group(1)
+              return (m.group(0)
+                      + '\t\t\t\tDEVELOPMENT_TEAM = "AAAAAAAAAA";' + eol
+                      + '\t\t\t\tCODE_SIGNING_ALLOWED = NO;' + eol
+                      + '\t\t\t\tCODE_SIGNING_REQUIRED = NO;' + eol)
+          s2 = re.sub(r'CODE_SIGN_STYLE = Automatic;(\r?\n)', repl, s)
+          open(p, 'w').write(s2)
+          print('patched' if s2 != s else 'NO CHANGE')
           PY
+          grep -n "CODE_SIGNING_ALLOWED" Runner.xcodeproj/project.pbxproj || echo "ALLOWED not found"
 
       - name: Build iOS (unsigned)
         run: |
